/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spacemonger1;

import spacemonger1.fs.FileSystems;
import spacemonger1.fs.linux.Glibc;
import spacemonger1.service.CFolderTree;
import spacemonger1.service.DrivesService;

import java.nio.file.Files;
import java.nio.file.Paths;

class AppTest {
    public static void main(String[] args) throws Exception {

        FileSystems fs = FileSystems.instance();
        DrivesService drivesService = new DrivesService(fs);
        CFolderTree tree = new CFolderTree(fs);
        Thread.ofPlatform().start(() -> {
            tree.LoadTree(drivesService.enumerateDrives().get(0));
        });
        while (true) {
            Thread.sleep(1000);
            System.out.println(tree.status());
            if (tree.status().tree() != null) break;
        }
        Thread.sleep(1005000000);
    }
}
