#!/bin/sh
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
exec "$SCRIPT_DIR/bin/java" -XX:+UseSerialGC -XX:+UseCompactObjectHeaders -XX:NewRatio=5 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -Xms64M --enable-native-access=spacemonger -m spacemonger/spacemonger1.App $1
